---
config:
  layout: dagre
  look: handDrawn
---
flowchart LR
 subgraph Backend["Backend"]
    direction LR
        B["Receptor (Broker HiveMQ)"]
        C["Interpretador (ESPTool)"]
        D["Clusterizador (Damicorepy)"]
  end
    A["Microcontrolador (ESP32)"] -- Envia Coredump via WiFi/MQTT --> B
    B -- Coredump validado --> C
    C -- Dados Estruturados (Stack Trace) --> D
    D -- Dados Classificados --> E[("Banco de Dados (SQLite3)")]
