---
config:
  layout: elk
  look: handDrawn
---
flowchart LR
 subgraph subGraph0["Receptor"]
        B{"Estrutura do pacote é válida?"}
        A["Recebe pacote de dados de entrada"]
        C["Extrai o coredump bruto e os metadados"]
        D["Descarta Coredump"]
        E{"Conteúdo (dados e metadados) é íntegro?"}
        F["Armazena o coredump bruto"]
  end
    A --> B
    B -- Sim --> C
    B -- Não --> D
    C --> E
    E -- Sim --> F
    E -- Não --> D
    ESP("Microcontrolador") -- Envia CoreDump --> A
    F -- Encaminha --> Interpreter("Interpretador")

%% Estilização
    style F fill:#c9ffc9,stroke:#333,stroke-width:2px
    style ESP fill:#c9c9ff,stroke:#333,stroke-width:2px
    style Interpreter fill:#c9c9ff,stroke:#333,stroke-width:2px
    style D fill:#ffc9c9,stroke:#333,stroke-width:2px